### ISSUE TITLE
 please set no_lazy_load true in your Chef configuration file

### ISSUE THREAD

**Issue by zanjibar** [poise/poise#12]
i got a error message "Halite is not compatible with no_lazy_load false, please set no_lazy_load true in your Chef configuration file." 

How can i prevent this error. 

I use these staff.
Chef Development Kit Version: 0.6.0
chef-client version: 12.3.0
berks version: 3.2.4
kitchen version: 1.4.0

**Comment by coderanger** [comment]
As the error says, set `no_lazy_load true` in your Chef config file (probably `/etc/chef/client.rb` unless you've changed the default).

**Comment by zanjibar** [comment]
create 
/etc/chef/client.rb

and write one line
Chef::Config[:no_lazy_load] = true

but  same error occure.

so I found a another client.rb in /opt/chefdk/embedded/apps/chef/lib/chef

and set like this
  class Client
    include Chef::Mixin::PathSanity
    Chef::Config[:no_lazy_load] = true

but same result.....

**Comment by coderanger** [comment]
What command are you running that you see the error? ChefDK is for workstations, not generally for servers.

**Comment by zanjibar** [comment]
I have 2 knife envritonment,
both same chefdk,cookbook but OS is differernt.

saime command  
knife solo cook xxx(target node)
CentOS 6.4 had error
Ubuntu 14.04 work fine

**Comment by coderanger** [comment]
Also it is worth noting that this error only triggers if you changed a default setting on your chef clients. The default values all work fine.

**Comment by coderanger** [comment]
You would need to edit the config on the target machine, not your workstation. Also make sure that the CentOS machine isn't running an older Chef.

**Comment by zanjibar** [comment]
I had run from 2 workstation (CentOS,Ubuntu)  'knife solo cook xxx' to one target machine.

target machine is Ubuntu 14.04 or 12.04.

I make /etc/chef/client.rb   "Chef::Config[:no_lazy_load] = true"
but same error.

**Comment by zanjibar** [comment]
I run once again "knife solo prepare xxx"  and work fine!

thank you for your answer.

**Comment by coderanger** [comment]
That is also not how you set config options for Chef. Please see [the Chef documentation](https://docs.chef.io/config_rb_client.html) for more information on that. If you are just getting started with chef, Poise is not a good place to start. It is a set of fairly advanced tools for building reusable cookbooks, but that still takes a lot of expertise.

**Comment by okram999** [comment]
I am not sure what bring 'poise' into berksfile.lock. But i see that there was an update of the file from the latest 'berks' command the cookbook firewall have been upgraded and then it pulled this poise as well.  

Then i started getting this error on the chef-client runs:

Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/poise/libraries/default.rb
================================================================================

RuntimeError
------------
Halite is not compatible with no_lazy_load false, please set no_lazy_load true in your Chef configuration file.

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/poise/libraries/default.rb:17:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/poise/libraries/default.rb:

 10:  # Unless required by applicable law or agreed to in writing, software
 11:  # distributed under the License is distributed on an "AS IS" BASIS,
 12:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 13:  # See the License for the specific language governing permissions and
 14:  # limitations under the License.
 15:  #
 16:
 17>> raise 'Halite is not compatible with no_lazy_load false, please set no_lazy_load true in your Chef configuration file.' unless Chef::Config[:no_lazy_load]
 18:  $LOAD_PATH << File.expand_path('../../files/halite_gem', __FILE__)
 19:


Running handlers:
[2015-06-19T07:59:09+00:00] ERROR: Running exception handlers
Running handlers complete
[2015-06-19T07:59:09+00:00] ERROR: Exception handlers complete
[2015-06-19T07:59:09+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 6.171321363 seconds
[2015-06-19T07:59:10+00:00] ERROR: Halite is not compatible with no_lazy_load false, please set no_lazy_load true in your Chef configuration file.
[2015-06-19T07:59:10+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)





Looking up the above comments, i modified the client.rb like this:

log_location     STDOUT
chef_server_url  "https://api.opscode.com/organizations/234-dev"
validation_client_name "234-dev-validator"
node_name "ec2-x.x.x.x.us-west-2.compute.amazonaws.com"
encrypted_data_bag_secret "/etc/chef/encrypted_data_bag_secret"
no_lazy_load true


Then, i got this next error.


  - python
  - poise
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/firewall/libraries/resource_firewall.rb
================================================================================

SyntaxError
-----------
/var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/option_collector.rb:89: syntax erro                                                                                                                  r, unexpected tLABEL
        def option_collector_attribute(name, default: {}, parser: nil)
                                                     ^
/var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/option_collector.rb:131: syntax err                                                                                                                  or, unexpected keyword_end, expecting $end

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/poise/files/halite_gem/poise/resource.rb:39:in `<module:Resource>'
  /var/chef/cache/cookbooks/poise/files/halite_gem/poise/resource.rb:34:in `<module:Poise>'
  /var/chef/cache/cookbooks/poise/files/halite_gem/poise/resource.rb:20:in `<top (required)>'
  /var/chef/cache/cookbooks/poise/files/halite_gem/poise/utils/resource_provider_mixin.rb:53:in `b                                                                                                                  lock (3 levels) in included'
  /var/chef/cache/cookbooks/poise/files/halite_gem/poise/utils/resource_provider_mixin.rb:53:in `c                                                                                                                  lass_exec'
  /var/chef/cache/cookbooks/poise/files/halite_gem/poise/utils/resource_provider_mixin.rb:53:in `b                                                                                                                  lock (2 levels) in included'
  /var/chef/cache/cookbooks/poise/files/halite_gem/poise.rb:54:in `include'
  /var/chef/cache/cookbooks/poise/files/halite_gem/poise.rb:54:in `block (2 levels) in Poise'
  /var/chef/cache/cookbooks/poise/files/halite_gem/poise.rb:54:in `class_exec'
  /var/chef/cache/cookbooks/poise/files/halite_gem/poise.rb:54:in `block in Poise'
  /var/chef/cache/cookbooks/firewall/libraries/resource_firewall.rb:5:in `include'
  /var/chef/cache/cookbooks/firewall/libraries/resource_firewall.rb:5:in `<class:Firewall>'
  /var/chef/cache/cookbooks/firewall/libraries/resource_firewall.rb:4:in `<class:Chef>'
  /var/chef/cache/cookbooks/firewall/libraries/resource_firewall.rb:3:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/poise/files/halite_gem/poise/resource.rb:

 32:    #     poise_fused
 33:    #   end
 34:    module Resource
 35:      include Poise::Helpers::ChefspecMatchers
 36:      include Poise::Helpers::DefinedIn
 37:      include Poise::Helpers::LazyDefault
 38:      include Poise::Helpers::LWRPPolyfill
 39>>     include Poise::Helpers::OptionCollector
 40:      include Poise::Helpers::ResourceName
 41:      include Poise::Helpers::TemplateContent
 42:
 43:      # @!classmethods
 44:      module ClassMethods
 45:        def poise_subresource_container(namespace=nil)
 46:          include Poise::Helpers::Subresources::Container
 47:          # false is a valid value.
 48:          container_namespace(namespace) unless namespace.nil?


Running handlers:
[2015-06-19T08:11:25+00:00] ERROR: Running exception handlers
Running handlers complete
[2015-06-19T08:11:25+00:00] ERROR: Exception handlers complete
[2015-06-19T08:11:25+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 13.851634911 seconds
[2015-06-19T08:11:26+00:00] ERROR: /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/                                                                                                                  option_collector.rb:89: syntax error, unexpected tLABEL
        def option_collector_attribute(name, default: {}, parser: nil)
                                                     ^
/var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/option_collector.rb:131: syntax err                                                                                                                  or, unexpected keyword_end, expecting $end
[2015-06-19T08:11:26+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited u                                                                                                                  nsuccessfully (exit code 1)


----------------------------

I dont intent to use poise, looks like the cookbook firewall pulled it down. I am also using the chef-client 11.18.12, on CentOS 6.6. 

Please let me know

**Comment by okram999** [comment]
The diff of the berksfile.lock 
-  firewall (0.11.8)		+  firewall (1.3.0)
+    poise (~> 2.0)
   iis (4.1.1)		   iis (4.1.1)

**Comment by coderanger** [comment]
@okram999 Please don't reuse closed tickets, but your issue is that Poise is not compatible with Chef 11, you'll need to downgrade your cookbooks or use Chef 12.
