### ISSUE TITLE
Rspec/Chefspec examples or documentation

### ISSUE THREAD

**Issue by pburkholder** [poise/poise#14]
Hi Noah -- Thanks for `poise`. When writing poise resources, how should one write spec tests? Can you document or point to example cookbooks that show patterns for this? Or does one just step_into the resource with chefspec the way we do with LWRPs?

Thanks, Peter

**Comment by coderanger** [comment]
Aside from dealing with `notifying_block`, there is nothing special about a Poise-based resource. Most of my cookbooks have spec tests you can look at using the [Halite spec helper tools](https://github.com/poise/halite#spec-helper), for example [the tests for poise_service_user](https://github.com/poise/poise-service/blob/master/test/spec/resources/poise_service_user_spec.rb). The Halite helpers automatically unwrap `notifying_block` so you can make assertions about internal resources. This is not great behavior and I would love to spend some time coming up with a better API for that, but haven't had the cycles. If you don't want to pull in the Halite spec helper (note that you can use the Halite helpers on a non-Halite cookbook just fine), you can use rspec-mocks to do a similar unwrap: `allow(Chef::Provider::MyThing).to receive(:notifying_block) {|&block| block.call }`. Beyond that I'm just careful about my `step_into` value and use a lot of complex matchers.

Also a lot of tests are easier without ChefSpec, just calling the code directly like a normal object with fully mocked node and/or run contexts. That style will be harder to use with a traditional (non-Halite) cookbook though.

**Comment by mhenrixon** [comment]
I can vouch for that! I stopped trying to test everything with chefspec and went for the unit test approach by using halite. Haven't regretted it a single time. I let the integration tests with server spec catch any run time error and keep chefspec to a minimum. Problem with chefspec is that the server runner is slow and the solo runner isn't good enough imho. Using halite, RSpec for unit tests, chefspec for testing chef stuff like include recipe and ServerSpec for the full Monty really does the trick for me.

**Comment by pburkholder** [comment]
@mhenrixon @coderanger Thanks for the pointers. I think I'm doing things I little more poise-ish at:

https://github.com/pburkholder/vault-cookbook/blob/pdb/poise_style/test/spec/libraries/vault_config_spec.rb

Could you let me if:
- there are helpers available for the code I have in the `before` block at https://github.com/pburkholder/vault-cookbook/blob/pdb/poise_style/test/spec/libraries/vault_config_spec.rb#L28
- there's a style for setting node attributes, e.g. what in chefspec we with `node.set['cookbook']['attribute'] = 'hello'`

I love using straight up RSpec though, and how blazing fast this is.

Thanks,

Peter

**Comment by coderanger** [comment]
There are no specific helpers for `include_recipe` or `chef_vault_item`. I use the former sparingly and the latter not at all so it hasn't come up much. Those look like the right way to do it though. 

For attributes, there are some limited `let` helpers: https://github.com/poise/halite/blob/master/lib/halite/spec_helper.rb#L63-L80. You would put something like:

```ruby
before do
  default_attributes['myapp']['url'] = 'http://testserver'
end
```

I'm not in love with this syntax and would like to add a more dedicated class-level helper which handles the deep merge for you, but I haven't gotten to it and that has been good enough so far. For cookbooks with complex attributes that you want to set for (almost) every test, check out [poise-service's spec helper for an example](https://github.com/poise/poise-service/blob/master/test/spec/spec_helper.rb#L22-L33). That just builds on the core `let` helpers with a little extra code.

**Comment by pburkholder** [comment]
Works for me. The right thing now is for me to submit a Getting Started for testing PR. Thanks for the guidance.

**Comment by coderanger** [comment]
You can always find the docs for the spec helper at http://www.rubydoc.info/github/poise/halite/master/Halite/SpecHelper
