### ISSUE TITLE
poise(2.0.1) is currently breaking on our chef-server

### ISSUE THREAD

**Issue by Thermatix** [poise/poise#17]
Specifically:

```ruby

def option_collector_attribute(name, default: {}, parser: nil)
```

This is becuase were using chef 11 which uses ruby 1.9.3 whereas that cose snippet is ruby 2.0.0, I would like to know, which is the last version of poise before this was introduced?

Also, were not directly using this cookbook, it's a dependency of a cookbook(elasticsearch) we are using. Not sure why it suddenly changed but it did around amonth ago, I'm trying to figure out what caused the version to change but I'm not having much luck. I mean obviously "elasticsearch" changed but I honestly can't seem to locate where.

**Comment by coderanger** [comment]
Poise, like all my cookbooks, requires Chef 12. Poise 1.x was the last version to support Chef 11.
