### ISSUE TITLE
Run container resource last, after all sub-resources

### ISSUE THREAD

**Issue by martinb3** [poise/poise#18]
Howdy @coderanger! Is there a way to make a container with subresources run _last_ instead of first? I'm in a situation where I'm using the parameters on subresources to collect some information. One important piece of information that I'd like to know is -- did an action actually run on the subresource? Once I know that, I'd like to see what subresources ran and what subresources didn't (perhaps due to an only_if that was false), so that I can do something in my container's action. Is that possible with poise? Or is there some other published interface to figure out if an action will run on a subresource, when running the container resource? I'd need something that covers the case where a guard using not_if/only_if was on a sub-resource. Thanks in advance!

**Comment by coderanger** [comment]
So the core problem is that subresources could be added "anywhere". If you only care about subresources created within the main block of the resource, you can override `after_created` and add a `ruby_block` resource there with some logic. If you want it to work with stuff created later, you're stuck in an arms race with how to be "last". One option is to use delayed notifications on self, another is to inject a resource at the end of the collection (though if you end up inside another resource, that might not be truly "last").

**Comment by martinb3** [comment]
I ended up going with delayed notifications. Thank you for the advice! I wish there was an in-built chef way to do this :)
