### ISSUE TITLE
Setting run_context.resource_collection will be removed in a future Chef. 

### ISSUE THREAD

**Issue by h4ck3rm1k3** [poise/poise#19]
I am getting this warning. I have a patch.
```
Setting run_context.resource_collection will be removed in a future Chef.  Use run_context.create_child
```
On this line:
 sub_run_context.resource_collection = Poise::Subcontext::ResourceCollection.new(parent_context.resource_collection)

https://github.com/poise/poise/blob/20f44e9e78e58a6f8084b7e17c4e5f3e2ea78111/lib/poise/helpers/subcontext_block.rb#L45

**Comment by coderanger** [comment]
Yeah, the warning will be removed. Disagreement between me and Chef as to what should be deprecated.

**Comment by h4ck3rm1k3** [comment]
Ok, well it seems my patch is working, need more testing.
