### ISSUE TITLE
Metadata.rb file are missing from source control

### ISSUE THREAD

**Issue by poliva83** [poise/poise#22]
Can the `metadata.rb` file can be added to this cookbook? I have a script that mirrored this repo internally but `berks` complains when trying to use mirrored git location as cookbook rule in top-level cookbook `Berksfile`.

It works when you get it from supermarket because for some reason the `metadata.rb` and `metadata.json` files are getting added before you push cookbook there.

The same issue affects `poise-ruby` and `poise-service` cookbooks.

Related
https://github.com/poise/poise-service/issues/6
https://github.com/poise/poise-ruby/issues/8

**Comment by cheeseplus** [comment]
Poise is a gem, not a cookbook - please see https://github.com/poise/poise/issues/11

**Comment by coderanger** [comment]
No, this cookbook is managed via Halite. See https://github.com/poise/halite#using-a-pre-release-version-of-a-cookbook for info on how to run from git directly.

**Comment by poliva83** [comment]
@coderanger @cheeseplus My apologies. This is first time I encountered cookbooks managed by Halite. I didn't realize you must "compile" the source to create a valid cookbook. Its sort of not expected when see cookbook on supermarket and click `view source` button. Seems there is no easy way to differentiate these types of cookbooks on supermarket. I'd maybe add a warning at top of project's readme file.

**Comment by coderanger** [comment]
@poliva83 Unfortunately the Chef community has trained people to think that running from git master is a normal thing to do. When things are ready for use in a way I'm comfortable with, I release them.

**Comment by bish0polis** [comment]
When people get used to what they're accustomed, a bit of a warning to limit surprises can often get us up to adequate.
