### ISSUE TITLE
Cannot upload cookbook to local supermarket.

### ISSUE THREAD

**Issue by yurylevin** [poise/poise#26]
Hi,

I'm trying to upload cookbook https://github.com/poise/poise to local supermarket and it fails because of missing metadata.rb. If it's right location of cookbook, could you please upload it? I have the same issue with poise-service.

Thanks,
Yury.

**Comment by coderanger** [comment]
As with all my cookbooks, the code in git is a gem that has to be converted to a cookbook before use. As you shouldn't be using Poise from master, you can download/reupload the existing releases from the main Supermarket site.

**Comment by yurylevin** [comment]
Hello,

How could I reupload cookbook from main supermarket site if it doesn't have
metadata.rb? There is metadata.json only.

Regards,
Yury.

2016-05-11 20:10 GMT+02:00 Noah Kantrowitz <notifications@github.com>:

**Comment by coderanger** [comment]
Download it from the main Supermarket, not GitHub. GitHub contains uncompiled source code that cannot be used directly.
