### ISSUE TITLE
notifying_block does not work with :before notifications

### ISSUE THREAD

**Issue by EdwardSkoviak** [poise/poise#28]
Noticed this with poise-archive, but before notifications don't look to be executed when using the notifying block. May be a result of this bug[1] in chef. This is the output from a chef-client run:

```
           * poise_archive[cerner_tomcat_my_tomcat-apache-tomcat.tar.gz] action unpack
             * Whyrun not supported for poise_archive[cerner_tomcat_my_tomcat-apache-tomcat.tar.gz], bypassing load.
       (Skipped: whyrun not supported by provider PoiseArchive::ArchiveProviders::GnuTar)
            (up to date)
        * poise_archive[cerner_tomcat_my_tomcat-apache-tomcat.tar.gz] action unpack
           * directory[/opt/my_dir/my_tomcat] action create
             - create new directory /opt/my_dir/my_tomcat
             - change owner from '' to 'my_user'
             - change group from '' to 'my_group'
             - restore selinux security context
```

Consequently, the before action passed to this resource never executed.

[1] https://github.com/chef/chef/issues/4537

**Comment by coderanger** [comment]
This is not related to poise itself, `poise_archive` does not support whyrun as the error says and `:before` timings require whyrun to operate. It would be nice to add to `poise_archive` but I have no specific plans to do so at this time.

**Comment by EdwardSkoviak** [comment]
So when using notifying block we need to make sure to override the why_run_supported method? Im sure my inexperience with chef is showing here, but I wouldve expected that to be functionality added in with the notifying_block so that before notifications would work.

**Comment by coderanger** [comment]
It isn't the use of notifying_block that specifically matters. All providers must explicitly opt-in to supporting whyrun because Chef can't know if they are safe to run or not. In the case of `poise_archive` it isn't safe because it hasn't been set up for whyrun mode. This requires some additional code in the provider to make sure it doesn't actually change the system ever.

**Comment by EdwardSkoviak** [comment]
Looking through the poise_archive source this makes much more sense to me now. Thanks for the quick response.

**Comment by coderanger** [comment]
It could definitely be added, it was just more work than not doing it and whyrun is so rarely used that I don't generally bother up front :)

**Comment by EdwardSkoviak** [comment]
I'm running into a semi-related issue, it seems the subresources will eat `before` notifications when the subresource is being used as a child of the container resource:

```ruby
parent_resource 'name' do
  sub_resource 'sub' do
    notify :action, resource, :before # nothing happens, nothing in chef-client run
  end
end
```

But interestingly when they being used standalone they seem to work.

```ruby
sub_resource 'sub' do
  parent 'name'
  notify :action, resource, :before # works as expected, i.e. whyrun execution, then before action, then runs
end
```

Maybe I'm doing something wrong here.

**Comment by EdwardSkoviak** [comment]
Should also note that `immediately` and `delayed` work in both of the above scenarios.

**Comment by coderanger** [comment]
`before` notification are both very new, and almost always a bad idea. Maybe jump on [Slack](https://community-slack.chef.io) and we can talk over what you are actually trying to do?

**Comment by EdwardSkoviak** [comment]
will do, see you on there
