### ISSUE TITLE
Providing helpers to the template

### ISSUE THREAD

**Issue by quulah** [poise/poise#32]
I'm trying to use PoiseService::ServiceMixin to create a configuration file (from a template) and a service.

I'd also like to provide helper modules to the template, and the list of modules can change depending on the service being created.

I'm currently pretty deep in the Chef code, trying to figure out how the TemplateContext stuff works. Before I poke any further and break things... Is there a clean way to provide the helpers with Poise? The [TemplateContent](https://github.com/poise/poise/blob/master/lib/poise/helpers/template_content.rb#L31) stuff seems to only handle variables.

I'm currently limited to Chef 12, if that makes any difference.

**Comment by coderanger** [comment]
I've not bothered with hooking in to the Chef systems for this since you can just straight up use normal Ruby code. https://github.com/poise/application_python/blob/master/chef/templates/settings.py.erb shows an example of using helper module methods in a template. The Erb is compiled in the same global namespace as other Chef code.

**Comment by coderanger** [comment]
(also TemplateContent is probably the cruftiest corner of my code and I apologize in advance for the terrible things you read :)

**Comment by quulah** [comment]
Ah, yeah. That would work too.

I'd rather not use the namespaced `Module::Module.stuff()` and just use `stuff()` in the templates so I ended up dropping the `attribute(:config, template: true)` from Poise and created the configuration with a template directly in the notifying_block. That let's me give anything directly to the template.

I'm missing on the Poise functionality now that let's you give the config file content through the resource without the template, but my intention was to have the users create templates for their configuration and grant them the opportunity to easily have helper module methods available.

But thanks any way! I'll think about this a bit and perhaps revert to using it like the application_python example.
