### ISSUE TITLE
How to test an lwrp inside a notifying_block?

### ISSUE THREAD

**Issue by mhenrixon** [poise/poise#7]
How can I test my Poise LWRP if it has a notifying_block?

https://gist.github.com/mhenrixon/b1cc5ab029ba737f95b0#file-test_helpers-rb

The code don't test ok if I have notifying_block but if I remove it the code tests fine.

**Comment by rhass-r7** [comment]
@mhenrixon The gist seems to have been deleted.

**Comment by mhenrixon** [comment]
You need to do something like:

```ruby
before do
    allow_any_instance_of(Chef::Provider::MultiSite)
      .to receive(:notifying_block) { |&block| block.call }
  end
```

**Comment by coderanger** [comment]
This is now built in to the Halite spec helper via the `step_into` helper. It is on by default https://github.com/poise/halite/blob/master/lib/halite/spec_helper.rb#L171-L187
