### ISSUE TITLE
Poise is broken under Chef 12

### ISSUE THREAD

**Issue by rhass-r7** [poise/poise#8]
NoMethodError is raised when making a call to remote_file in Chef 12

```
NoMethodError       
    -------------       
    undefined method `remote_file'  .......
```

**Comment by martinb3** [comment]
Is this fix for this to add the include everywhere in poise? I'm wanting to use this but stuck on the chef 12 issue, and wondering how I can help with a PR :)

**Comment by rhass-r7** [comment]
@martinb3 Pull Request #9 should have fixed the issues -- I haven't tested the new version in my cookbook yet because it hadn't been released to the supermarket when I last looked. Nevertheless, here is an example use of the workaround: 

https://github.com/rapid7-cookbooks/firefox_package/blob/master/libraries/firefox_package.rb#L36-L37

If you find other stuff broken as result of Chef 12 changes, please let us all know! =)

**Comment by coderanger** [comment]
This is fixed.
